workflows:
  android-workflow:
    name: Expense Tracker Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

      - name: Build App Bundle
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - prakharmishraspn91@gmail.com

